spring:
  application:
    name: laobeiblog-server
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0
    url: jdbc:mysql://1.1.1.3:3306/laobeiblog?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 20MB #文件上传单个文件限制大小
      max-request-size: 100MB #文件上传多个文件限制大小

  # redis
  data:
    redis:
      host: 1.1.1.3
      port: 6379
      database: 0

#自定义线程池
thread:
  corePoolSize: 4
  maximumPoolSize: 20
  keepAliveTime: 60
  workQueueLength: 100

aliyun:
  endpoint: "https://oss-cn-shenzhen.aliyuncs.com"
  accessKeyId: "xxx"
  accessKeySecret: "xxx"
  bucketName: "orange-product-my"
  host: "https://orange-product-my.oss-cn-shenzhen.aliyuncs.com"
  dir: "laobeiblog"