server:
  port: 8001
springdoc:
  packages-to-scan: com.xi.controller #包扫描,这里需要写你的真正接口的包也就是controller
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 邮件
spring:
  mail:
    host: smtp.163.com
    username: lb16673514910@163.com
    password: xxx