spring:
  application:
    name: laobeiblog-server
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0
    url: jdbc:mysql://1.1.1.3:3306/laobeiblog?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  mybat